language: node_js
node_js:
  - "10"
install:
  - yarn add --dev vuepress
script:
  - yarn build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
